language: python

python:
  - "3.7.5"
#   - "3.8-dev"

env:
  - TEST_SUITE=testOnlyDocTests
  - TEST_SUITE=test

# TODO: Add pip back to this cache somehow, either `pip` or its dir
cache:
  directories:
    - $HOME/stanza_resources/
    - $HOME/cltk_data/
    - $HOME/virtualenv/

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - make install
#  - poetry run python scripts/download_misc_dependencies.py
# TODO: re-enable

before_script:
  - poetry run pre-commit install-hooks
#  - poetry run pre-commit run --all-files

#script: "bundle exec rake test:$TEST_SUITE"
script:
  - make $TEST_SUITE
#  - make testOnlyDocTests
#  - make test

after_success:
  - echo Add later

after_failure:
  - echo Add later
