language: python

python:
  - "3.7.5"
#   - "3.8-dev"


cache:
  - pip
  directories:
    - /home/travis/stanfordnlp_resources/
    - /home/travis/cltk_data/


before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - make install
  - poetry run python scripts/download_misc_dependencies.py


before_script:
  - poetry run pre-commit install-hooks
#  - poetry run pre-commit run --all-files

script:
  - make test

after_success:
  - echo Add later

after_failure:
  - echo Add later
