language: python

python:
  - "3.7.5"
#   - "3.8-dev"

cache:
  - pip
  - /home/travis/stanfordnlp_resources/
  - /home/travis/cltk_data/

# TODO: Improve the order of these
before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install -v
  - poetry run python scripts/download_misc_dependencies.py


before_script:
  - poetry run pre-commit install-hooks
#  - poetry run pre-commit run --all-files

script:
  - poetry run pytest --doctest-modules --cov-report term-missing --cov-report html:htmlcov --cov=src/cltkv1 src/cltkv1/ tests/

after_success:
  - echo Add later

after_failure:
  - echo Add later
