sudo: required

language: python

python:
  - "3.6"

install:
  - python setup.py sdist install

before_script:
  - pip install --upgrade pip
  - pip install codecov
  - pip install coveralls
  - pip install pandas  # for the Indian syllabifier
  - pip install greek-accentuation  # for the phonetic transcriber
  - pip install fuzzywuzzy
  - pip install python-Levenshtein
  - pip install PyArabic  # for Arabic in tokenize/word.py
  - pip install gensim # for word2vec.py

script:
  # Notes on nose:
  # Travis CI pre-installs `nose`
  # https://github.com/coagulant/coveralls-python#nosetests
  # http://nose.readthedocs.org/en/latest/plugins/skip.html
  - nosetests --no-skip --with-coverage --cover-package=cltk --with-doctest

after_success:
  - codecov

deploy:
  - provider: pypi
  - user: "kyle_johnson"
  - password: ""
    - secure: "qBNTRm7RgcXFIqNIN2pEN2bm6mhuNJC9vXyZOKUpWdjPrcKoAYSCoCKMa/YuhKowMW9NHHjakbU7T3sJJb15GsAE0JkrQ7dfk5baqA9E9Wgsis++/qJ0LxgRvZAypNxHsl+Ofx9RDJnTi7LGFkVU4QqmYyYDuC7x1NE4jU+4h3M="
  - on:
    - branch: master
    # - tags: true
